function ResultsALL6activities0 = importfileALL6activities(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RESULTSALL6ACTIVITIES0 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  RESULTSALL6ACTIVITIES0 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ResultsALL6activities0 = importfileALL6activities("C:\Users\luis.sigcha\Documents\MATLAB\EMA LABELLING\MAIN STUDY ICAMPAMP\Results_ALL6activities_0.5threshold_FULL_2025-01-29 17-10-44_V2NO_survey_filter.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Feb-2025 14:02:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Accuracy", "number_questionnaires", "data_length", "plannedId", "file_name", "activity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "activity", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "file_name", "TrimNonNumeric", true);
opts = setvaropts(opts, "file_name", "ThousandsSeparator", ",");

% Import the data
ResultsALL6activities0 = readtable(filename, opts);

end